### ISSUE TITLE
I keep getting this error during the build.

### ISSUE THREAD

**Issue by TsangKalung** [Cubelrti/AutoWifiAuth#1]
The error is that:

> 无法在当前用户的 Windows 证书存储中找到代码签名证书。若要更正此问题，请禁用 ClickOnce 清单的签名或将证书安装到证书存储中。 （迫真）

I think remove the "signature for ClickOnce list" in the signature tab of project properties. When ClickOnce is published, it is generally required to sign the list, and the certificate of the project is empty, and it is sure that the certificate will not be found on the machine at compile time.

**Comment by Cubelrti** [comment]
fixed by 3047125e7069d426e0c2f1c827573e922dd452af. 

谢谢🍆
